version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  required:
    - build
    - repo
toolchain:
  name: 'mytodos-{{timestamp}}'
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'mytodos'
      repo_url: 'https://github.com/lionelmace/mytodo'
      type: clone
      has_issues: false
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: 'mytodos ({{form.pipeline.parameters.branch-name}})'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          GIT_BRANCH: '{{form.pipeline.parameters.branch-name}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.target-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          IMAGE_NAME: '{{form.pipeline.parameters.image-name}}'
          TARGET_REGION_ID: '{{form.pipeline.parameters.target-region}}'
          TARGET_CLUSTER_NAME: '{{form.pipeline.parameters.target-cluster-name}}'
          TARGET_NAMESPACE: '{{form.pipeline.parameters.target-cluster-namespace}}'
          TARGET_RESOURCE_GROUP: '{{form.pipeline.parameters.target-resource-group}}'
        execute: true
form:
  pipeline:
    parameters:
      image-name: 'mytodos'
      target-cluster-namespace: mytodos
      target-resource-group: 'default'
      branch-name: 'master'
    schema:
      $ref: deploy.json